### ISSUE TITLE
Missing .rubocop.yaml configuration file in deliverable2.md

### ISSUE THREAD

**Issue by zack-hable** [laboon/CS1632_Spring2019#10]
in deliverable2.md:
> This program must be written in Ruby and use minitest for the unit tests. This program must use rubocop with the attached .rubocop.yml configuration and SimpleCov as described in class.

> 

I don't see the attached file in the repo.  Would you mind uploading a copy?

**Comment by laboon** [comment]
Fixed in commit 8b741bc4cf458333071c113af7fd1ae13f0fe828

Please write "+1 ISSUE #10" on your D2 cover sheet for a bonus point.
