### ISSUE TITLE
Deliverable 2 Output: Max Rubies/Fake Rubies Range Concern

### ISSUE THREAD

**Issue by MisterZW** [laboon/CS1632_Spring2019#12]
The sample output provided for deliverable 2 seems to show only values in the range of [0 - (max_rubies - 1)] and [0 - (max_fake_rubies - 1)]. 

That is, the program never seems to find the maximum number of rubies or fake rubies in spite of the requirements stating that this should be possible. For example, the Rubyists never find anything in Enumerable Canyon in any of the sample outputs.

Seems unlikely that it's a coincidence. Thanks!

**Comment by laboon** [comment]
Yeah, I had an off-by-one error.  Fix incoming.  Please add "+2 ISSUE #12" to your cover sheet for D2 for 2 bonus points.
