### ISSUE TITLE
Typo in D2, sample_output.txt

### ISSUE THREAD

**Issue by jaredclin** [laboon/CS1632_Spring2019#16]
Usage says gold_rush.rb instead of ruby_rush.rb

[laboon@ekaterina ~/pitt/pitt_private/ruby_rush]
(20052) $ ruby ruby_rush.rb -9 -9 -9
Usage:
ruby **gold_rush.rb** *seed* *num_prospectors* *num_turns*

**Comment by laboon** [comment]
Fixed in commit `40d7979`.  Please write +1 ISSUE #16 on your D2 deliverable cover sheet for a bonus point.
