### ISSUE TITLE
Reference to each Rubyist in sample_output.txt missing #.

### ISSUE THREAD

**Issue by constantinoflouras** [laboon/CS1632_Spring2019#17]
In the requirements.md file, requirement #14 states that each Rubyist must be named as such:

> Prospectors shall be named "Rubyist #n" where n is their number, starting with #1 (there shall be no Rubyist #0).

Within the sample_output.txt file, Rubyists are referred to without the preceding # before the number.
For example, on line 124, it reads:
(Observed:)
> After 55 days, Rubyist 1 found:

Another instance of this is on line 142.
> After 12 days, Rubyist 2 found:

To meet requirement #14, this should be adjusted to the following at the conclusion of each rubyist's turn:
(Expected:)
> After 55 days, Rubyist #1 found:
> After 12 days, Rubyist #2 found:

Notice the addition of the #. This appears at each output instance of the sample_output.txt file.

Not sure if this is nitpicky-- but to keep the output consistent, I believe this should be adjusted.

**Comment by constantinoflouras** [comment]
To clarify-- this specifically occurs not at the beginning of each Rubyist's adventure, but rather when data about the conclusion is being printed out (aka all occurences of "After {number_of_days} days, ...")

**Comment by laboon** [comment]
It's nitpicky, but QA is nitpicky. =) I will update the requirements to indicate that either #n or n are acceptable, e.g., "Rubyist 1" or "Rubyist #1" are acceptable variants.

Please write +1 ISSUE #17 on your deliverable 2 cover sheet for a bonus point on D2.
