### ISSUE TITLE
[D2] Duplicate Attribute in rubocop config file

### ISSUE THREAD

**Issue by ajhenry** [laboon/CS1632_Spring2019#18]
In ` CS1632_Spring2019/deliverables/2/.rubocop.yml`, there is a duplicate attribute that results in a warning when running rubocop

Duplicate Attribute
```yaml
Metrics/PerceivedComplexity:
    Max: 30
```

Warning
```ssh
.rubocop.yml:10: `Metrics/PerceivedComplexity` is concealed by line 16
```

**Comment by laboon** [comment]
Yeah, this warning didn't show up with my version of rubocop but does show up on the latest.  I fixed this already although I can't find the commit.  Ordinarily I would give you +1 point on D2, but to make up for how long it took to get this looked at (after you turned in D2!), I will give you +0.5 percent on your final grade.
