### ISSUE TITLE
[D2] Ruby version requirements not specified in .rubocop.yml, unnecessary warnings for valid code

### ISSUE THREAD

**Issue by constantinoflouras** [laboon/CS1632_Spring2019#21]
In D2, I observed that running Rubocop against code with a safe navigation operator (&), a Ruby 2.3 feature, with the supplied .rubocop.yml file results in a warning:
```
test.rb:5:37: E: Lint/Syntax: unexpected token error
(Using Ruby 2.2 parser; configure using TargetRubyVersion parameter, under AllCops)
  return nil if arr.nil? || arr[num]&.name.nil?
                                    ^^
```
Note how in this output, it states that the Ruby 2.2 parser is used. As stated in the project description, code should be written and run for Ruby 2.50. These statements shouldn't be considered invalid.

Here's a simple test snippet of code:

```ruby
# frozen_string_literal: true

#   Sample code
def get_arr_element_name(arr, num)
  return nil if arr.nil? || arr[num]&.name.nil?
end
```
**Precondition:** 
- Ruby 2.50 and Rubocop 0.64.0 are successfully installed.
- OS: Windows 10 x64-based system; or Chrome OS 72.0.3626.117 (64-bit)

**Expected Behavior:** The Ruby 2.5 parser is used.
**Observed Behavior:** The Ruby 2.2 parser is used, thus, throwing a warning due to an "unknown character" &.
**Steps to Reproduce:**
1) Pull the current repository
2) Create a file called test.rb, containing the above snippet of code, within the D2 directory.
3) In a terminal, run "rubocop test.rb"

**Post-condition:**
The warning, as shown above, will appear on the console.

**Suggested Solution:** (this worked for me-- but I'm certain I'm not supposed to modify this) Modifying the .rubocop.yml file to explicitly use the Ruby 2.5 parser by adding the following lines to the file solved this issue:

```
AllCops:
  TargetRubyVersion: 2.5
```

I understand this is most likely a Rubocop bug (or perhaps a design decision?), but nonetheless, the .rubocop.yml should be updated for this project to reflect the version that we will be working with.

--update 3/5/2019 10:19AM-- fixed a bug within the sample source code, specified version number of Rubocop--

**Comment by laboon** [comment]
I don't see this on my machine - can you tell me which rubocop version you are running ("rubocop -v")?

**Comment by constantinoflouras** [comment]
This is running on my Windows 10 64-bit machine:
```
rubocop -v
0.64.0
```

**Comment by constantinoflouras** [comment]
There was an error in the previous source code that I had posted. I've fixed that, added the version number of Rubocop to the original issue, and the operating system(s) that I am using/have tried.

**Comment by laboon** [comment]
This looks like something that started after my current version of rubocop (0.52).  I upgraded to 0.66 and saw it.  I added your fix in.

I have given you +0.5 % overall extra credit (i.e. +0.5 percentage point on your final grade) for this excellent defect report.  Thanks.
