### ISSUE TITLE
Minor D3 requirement inconsistency

### ISSUE THREAD

**Issue by MisterZW** [laboon/CS1632_Spring2019#26]
Requirements 5 & 6 mention adding three additional columns for AND, OR, NOR, and NAND. That would make four additional columns.

**Comment by laboon** [comment]
Off-by-one errors are pretty common in CS, aren't they?

Please write +1 ISSUE #26 on the cover sheet of your D3 deliverable for an extra credit point and thank you for filing!

**Comment by constantinoflouras** [comment]
Requirement 6 was not fixed-- I've issued a pull request to fix this
