### ISSUE TITLE
Typo in Deliverable 3

### ISSUE THREAD

**Issue by jdsigg** [laboon/CS1632_Spring2019#27]
In the D3 file named deliverable3.md, the word "DUE" is missing. The exact text is:

ASSIGNED 18/19 MAR (MW/TH); 1/2 APR (MW/TH)

**Comment by laboon** [comment]
Thanks.  Fixed in commit ee30b61.  Please write +1 ISSUE #27 on the cover sheet of your deliverable for +1 extra credit.
