### ISSUE TITLE
Deliverable 3 Katalon Recorder vs Studio

### ISSUE THREAD

**Issue by FrowntownPitt** [laboon/CS1632_Spring2019#30]
There is no specific mention of what form of Katalon to use.  Please specify that we are to use Katalon _Recorder_ and **NOT**  _Studio_.  After asking, it was explained that _Studio_ generates files that are not able to be graded, and that *Recorder* is **required**.

**Comment by FrowntownPitt** [comment]
As a side effect, it is not possible to ensure a `404 Error` code is returned with _Recorder_, making requirement 8 impossible to completely satisfy. _Studio_ supports this feature.

**Comment by laboon** [comment]
I do not think this is necessary, as:

1. Katalon Studio is a program which is never mentioned in any class, any reading in the textbook, or any previous assignment.  
2. Katalon Automation Recorder _is_ used and specified in Exercise 5, which is supposed to have been done before Deliverable 3. https://github.com/laboon/CS1632_Spring2019/blob/master/exercises/5/exercise5.md 
3. In our web testing lectures, not only do we discuss Katalon Automation Recorder in-depth, but the slides specifically point to how to install it, which browsers are preferred, etc.  Even if someone misses class both that day and the day of the exercise, they should be able to determine what they missed by a) doing the exercise, b) asking for notes, or even just c) reviewing the lecture slides (https://github.com/laboon/CS1632_Spring2019/tree/master/lectures) for that day.  As mentioned on the first day of class:

"Lecture attendance is not required, but is STRONGLY recommended. The instructor will try to ensure that all information on the exams and projects will be available via slides, but simply reading the slides and textbook may be insufficient to understand the concepts thoroughly. " -Source: https://github.com/laboon/CS1632_Spring2019/blob/master/course-info.md (Although in this case the relevant information actually is on the slides.

If the 404 check cannot be done with KAR, one could perform a manual test to see what is returned, or mention in the write-up that this particular aspect could not be tested (recall that write-ups are used for mentioning issues that you encounter when writing/executing the tests and are required for each deliverable).

**Comment by FrowntownPitt** [comment]
Understood. My mistake.
