### ISSUE TITLE
Missing Exercise Solutions for 4 and 5

### ISSUE THREAD

**Issue by acd53** [laboon/CS1632_Spring2019#31]
Do exercises 4 and 5 have solutions that you would be able to post?

**Comment by laboon** [comment]
Sorry about this - thought they were up already!  Let me know your name and class meeting time and you'll get extra credit for bringing this to my attention.

**Comment by laboon** [comment]
And they were just posted in commit 8d696dd267b75e0d984349b2e811f9e86fd3468e

**Comment by acd53** [comment]
Alexandra Dziak ; MoWe 1:00 class

**Comment by laboon** [comment]
OK extra credit will be added to your final grade.  The CourseWeb column "EC" has been updated.
