### ISSUE TITLE
Deliverable 4 - Output

### ISSUE THREAD

**Issue by ajfortuna97** [laboon/CS1632_Spring2019#34]
In _sample-output.txt_, it is missing the addresses 039873 and 070668, both of which have 0 billcoin at the end of _sample.txt_'s run. The current instructions do not specify if having 0 billcoin means you should be omitted from the final output, which seems to be the case according to _sample-output.txt_.

**Comment by laboon** [comment]
Fixed in commit 008afa7eb01df373a30de059a476bc45e3ee86a1

Please write "+1 ISSUE #34" on the cover page of your D4 for +1 extra credit for your group
