### ISSUE TITLE
Stackprof will not properly compile/install for Windows

### ISSUE THREAD

**Issue by ajfortuna97** [laboon/CS1632_Spring2019#36]
I refer to this issue here: https://github.com/tmm1/stackprof/issues/45

When I attempt _gem install stackprof_, I run into the same error (as attempting to run the program without stackprof gives a _Please require the stackprof gem falling back to fast-stack._, and then installing stackprof results in this). The stackprof repository has been noted to require a Linux-based OS as well, which is also noted in the issue link above.

I'd like to suggest a note be made on the .md files of the exercise 6 and of the flamegraph sample code, since you can get around this by doing _gem install fast\_stack_, although the program will still output "Please require the stackprof gem falling back to fast\_stack." It will however, still run.

**Comment by laboon** [comment]
I believe this already exists in the exercise6.md file: "If you get an error installing stackprof, try installing fast_stack via the command line - `gem install fast_stack`."  Is it not showing up for you?

**Comment by ajfortuna97** [comment]
Just didn't scroll down far enough, or I must've overlooked it while reading. Sorry about that!

**Comment by laboon** [comment]
No worries!  Let me know if you have any other trouble running the exercise.
