### ISSUE TITLE
Excercise 7 Stock Prices Downcased when Should be Upcased

### ISSUE THREAD

**Issue by jrutkauskas** [laboon/CS1632_Spring2019#37]
In Excercise 7 trade_engine.rb, in buy_a_stock and sell_a_stock, the code should be stock = gets.chomp.upcase instead of gets.chomp.downcase.

Otherwise, it will fail because we access the prices hash directly.  Property-based testing of market.rb will never be able to catch this error.

**Comment by laboon** [comment]
Fixed in commit b6251aca.  +0.5 extra credit added on courseweb.
