### ISSUE TITLE
D4 - billcoin.md

### ISSUE THREAD

**Issue by wenqianz** [laboon/CS1632_Spring2019#38]
In D4, billcoin.md
For the timestamp, it should never be the same or move "backwards in time".
In the invalid blockchain example:
2. Timestamp does not increase monotonically (make sure you understand the timestamp format!)
If the timestamp does Increase monotonically it would mean that could remain the constant time.
It should be: Timestamp does not increase **strictly** or Timestamp increase monotonically.

**Comment by laboon** [comment]
You're right - mistake on my part.  Please write +1 ISSUE #38 on the cover page of D4 for a bonus point for your group.
