### ISSUE TITLE
Typo in the Text Book

### ISSUE THREAD

**Issue by MicahAnthony** [laboon/CS1632_Spring2019#4]
**Grammatical Error**
Chapter 6 pg 40 (Above Input Values section): 

_"This is not only because the system itself is much more complex, but also because a failure would be much significant for the bank system than the image-sharing system."_

Solution: 
_"This is not only because the system itself is much more complex, but also because a failure would be much **more** significant for the bank system than the image-sharing system."_

![image](https://user-images.githubusercontent.com/35321994/51398083-a5681800-1b10-11e9-8036-20a4f57edc1a.png)

**Comment by laboon** [comment]
Thanks, Micah.  In the future please file issues on the book on the laboon/ebook repository.

I have fixed this typo on commit 5adeab09856781dd99da73cf51cf800511deccd7 there.

+0.5% extra credit on the final grade for you.
