### ISSUE TITLE
Inconsistencies between billcoin.md and deliverable4.md regarding system requirements

### ISSUE THREAD

**Issue by constantinoflouras** [laboon/CS1632_Spring2019#41]
Found in conjunction with @navdeephanda

In deliverable4.md, the third paragraph states that
> This will be run on a four-core system with eight gigabytes of RAM.

In billcoin.md, the second to last paragraph states that
> The target and threshold should be calculated based on a a 2.3 GHz Macbook Pro with 16 GB of RAM, running no other programs besides necessary system daemons and the like.

These statements are inconsistent with each other (notably, the amount of system RAM). In order to optimize our code in the best way possible, we need to have consistent machine specifications.

**Comment by laboon** [comment]
Please write +1 ISSUE #41 on your cover sheet for D4 for an extra credit point for your group
