### ISSUE TITLE
Midterm preparation material

### ISSUE THREAD

**Issue by jeremykato** [laboon/CS1632_Spring2019#42]
![LABOON 5 me_irl](https://user-images.githubusercontent.com/14220765/55847593-e3754680-5b17-11e9-9c2b-88ed8ab7bb61.png)

**Comment by jeremykato** [comment]
@laboon

**Comment by navdeephanda** [comment]
this is so woke

**Comment by Tivieta** [comment]
I'm sorry that I've contributed in a small way to this

**Comment by Tivieta** [comment]
Tag urself which laboon are you
I'm laboon looking up 2 to the right.

**Comment by navdeephanda** [comment]
I'm the first laboon

**Comment by jaredclin** [comment]
missed opportunity to sneak misurda in there
![image](https://user-images.githubusercontent.com/21224536/55850700-7667ae00-5b23-11e9-857c-d8a813786271.png)

**Comment by laboon** [comment]
I am sad that this issue is now closed.
