### ISSUE TITLE
D4 Gemfile

### ISSUE THREAD

**Issue by devoncallanan** [laboon/CS1632_Spring2019#44]
I would be awesome if the D4 Gemfile included `gem "fast_stack"` for us Windows plebs that didn't do the in class exercise.

**Comment by MarkFilus** [comment]
There's no Gemfile, but they are extremely simple.

```Gemfile
source "https://rubygems.org"

gem "minitest"
gem "simplecov"
gem "rubocop"
gem "rubocop-performance"
gem "flamegraph"
gem "fast_stack"
gem "rantly"

ruby "~> 2.5"
```

**Comment by laboon** [comment]
I added it to the example Gemfile for /sample_code/flamegraph_example in commit bab505ab29a73d5e50942ac40d15f378aef0104d

Note that rubocop-performance is _not_ necessary (but it might not be a bad idea to get those cops in as well...) 

Please write +1 ISSUE #44 on your D4 cover sheet for a bonus point for your group
