### ISSUE TITLE
D4 rubocop Frozen String Literals

### ISSUE THREAD

**Issue by nicksmider** [laboon/CS1632_Spring2019#45]
D4 specifies we must use the provided .rubocop.yml file.

I would like to append the following rule with permission:

`Style/FrozenStringLiteralComment:
  Enabled: false`

This behavior is default by Ruby, and adding this rule keeps rubocop from requiring a specification at the top of every file. 

I'm not sure if it is just my Rubocop that is experiencing it, but it needs to be set true or false either way, and making a rule would keep us from doing it in every file.

**Comment by laboon** [comment]
Good idea, please write +1 ISSUE #45 on the cover sheet of your deliverable for a bonus point on D4 for your group
