### ISSUE TITLE
Typo in D4

### ISSUE THREAD

**Issue by cnm31** [laboon/CS1632_Spring2019#46]
the second paragraph of deliverable4.md states the following: 

The program shall accept one argument, which is the name of a file which should contain a valid Billcoin blockchain (see billcoin.md in this directory for the rules of Billcoin). Your program will read in and either determine if it is valid (in which case you should print out all of the **address** which have billcoins and how many), or invalid (in which case you should print out what the error is).

singular "address" should be "addresses"

**Comment by laboon** [comment]
Please write +1 ISSUE #46 on your D4 cover sheet for a bonus point
