### ISSUE TITLE
Typo in D2, requirements.md

### ISSUE THREAD

**Issue by ajfortuna97** [laboon/CS1632_Spring2019#7]
Current Text: The program shall be run by typing `ruby ruby_rush.rb` at the command line along with **two** arguments, the `seed`, `the number of prospectors`, and `the number of turns`, in that order.

Should this read three arguments instead? The next two sentences read 

> All arguments shall be integers. If there are not three arguments, the arguments cannot be interpreted as integers

Just wanted to do a sanity check that I'm not misinterpreting the number of arguments that we're supposed to support.

**Comment by laboon** [comment]
Correct, should be three.  Please reference this issue on your cover page for a bonus point on the assignment.

**Comment by laboon** [comment]
(fixed in commit  6916e68 )
