### ISSUE TITLE
Possible Typo in life.rb

### ISSUE THREAD

**Issue by jeremykato** [laboon/CS1632_Spring2019#8]
On line 73 of `life.rb`, there is the following line:

`# All of these can be done`

However, there is no further context besides this line - is this to inform us that anything is possible through the power of friendship and Ruby, or a typo?

**Comment by laboon** [comment]
Typo - it should have said:

```
# All of these can be done in one line.
```

Please note this Issue #8 on the cover of your D2 deliverable for +1 bonus point.

**Comment by laboon** [comment]
But you are correct that anything is possible through the power of friendship and Ruby.
