### ISSUE TITLE
Typo in D2, requirements.md

### ISSUE THREAD

**Issue by zack-hable** [laboon/CS1632_Spring2019#9]
> The seven locations on the map shall be as follows: ~~Sutter Creek~~Enumerable Canyon, which connects to Duck Type Beach and Monkey Patch City; Duck Type Beach, which connects to Enumerable Canyon and Matzburg; Monkey Patch City, which connects to Nil Town, Enumerable Canyon, and Matzburg; Nil Town, which connects to Monkey Patch City and Hash Crossing; Matzburg, which connects to Monkey Patch City, Duck Type Beach, Hash Crossing, and Dynamic Palisades; Hash Crossing, which connects to Matzburg, Nil Town, and Dynamic Palisades; and Dynamic Palisades, which connects to Matzburg and Hash Crossing. It may be easier to view a graphical depiction of the map:
> 
I don't see any reference to Stutter Creek in the depiction of the graph and think its referring to Enumerable Canyon.

**Comment by laboon** [comment]
Yeah, this was a typo (or think-o).  I have fixed it in the referenced commit.

Please write "+1 ISSUE #9" on the cover of your D2 for a bonus point.
